apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    service: timemachine-{{USER}}
  name: timemachine-{{USER}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1002Gi
status: {}
