apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: timemachine-{{USER}}
  name: timemachine-{{USER}}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: timemachine-{{USER}}
    spec:
      containers:
      - image: {{YOUR_REGISTRY/USERNAME}}/timemachine
        name: timemachine-docker
        ports:
        # - containerPort: 137
        #   protocol: UDP
        # - containerPort: 138
        #   protocol: UDP
        # - containerPort: 139
        - containerPort: 445
        resources: {}
        volumeMounts:
        - mountPath: /backup/timemachine
          name: timemachine-{{USER}}
      imagePullSecrets:
      - name: beuth-gitlab-auth
      restartPolicy: Always
      volumes:
      - name: timemachine-{{USER}}
        persistentVolumeClaim:
          claimName: timemachine-{{USER}}
status: {}
